---
title: Running mechanics and injury
author: Aleksis
date: '2020-04-19'
slug: running-mechanics
categories:
  - fitness
tags:
  - Fitness
  - Running
subtitle: ''
description: ''
image: ''
showtoc: FALSE
draft: TRUE
---

I have had a love-hate relationship with running since adolescence. Due to a parental requirement that I participate in a sport or activity, I found myself deciding what sport to join after I had decided to drop out of boy scouts. After an abysmal run-in with the sport of golf, I decided to run track. However, this being the fall of my freshman year, I was convinced by a friend to join cross country. I joined cross country and never ran track - reasoning that I ran enough during the summer (to prepare for cross country) and fall (the cross country season) that I didn't need to run anymore in the spring. 

In retrospect, track may have been a better fit. I love sprinting and olympic lifts like the clean and jerk, both of which are more fitting for a short-distance track athlete than a marathoner. However, I struggled through four cross country seasons, collecting a number of annual injuries and eventually competed at the state level. When I finished high school I decided to forego cross counry, despite recruitment attempts by a coach at the college I would end up attending. 

## Injury rates